Finished project
webmarkyn/ruby-solo-1 pull request #1
Opened 2019-10-10 22:21 UTC by webmarkyn

2019-10-11 20:39 UTC, samgaco requested changes
Hi @webmarkyn :high_brightness: 

I leave some comments on what functionalities your methods are lacking. You can find a reference of how they are expected to work [here](https://ruby-doc.org/core-2.6.4/Enumerable.html).

Please, work on these required comments and submit them back for another code review once you are done.

------------------------
Moving on :arrow_down: 

* **[For your next code review requests]**  Add a short summary of changes in Pull Request description
-----------------------
* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-11 20:39 UTC, samgaco commented on main.rb
> +    end
- [ ] my_each returns an Enumerator if no block is given

2019-10-11 20:39 UTC, samgaco commented on main.rb
> +    end
- [ ] my_each_with_index returns an enumerator if no block is given

2019-10-11 20:39 UTC, samgaco commented on main.rb
> +      temp << self[i] if yield(self[i])
- [ ] my_select returns an enumerator if no block is given

2019-10-11 20:39 UTC, samgaco commented on main.rb
> +        return false unless yield(item)
- [ ] my_all? when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-10-11 20:39 UTC, samgaco commented on main.rb
> +      return true if item && !block_given?
- [ ] my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-10-11 20:39 UTC, samgaco commented on main.rb
> +        return false if yield(item)
- [ ] my_none? when no block or argument is given returns true only if none of the collection members is true
- [ ] my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] my_none? when a Regex is passed as an argument returns true only if none of the collection matches the Regex

2019-10-11 20:39 UTC, samgaco commented on main.rb
> +      if block_given? && yield(item)
- [ ] my_count returns the number of items in enum through enumeration

2019-10-11 20:39 UTC, samgaco commented on main.rb
> +      temp << [proc.call(self[i])] if proc
- [ ] my_map returns a new array with the results of running block once for every element in enum.
- [ ] my_map returns an Enumerator if no block is given

2019-10-11 20:39 UTC, samgaco commented on main.rb
> +    end
- [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
- [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-10-16 11:43 UTC, stratospherique requested changes
> ### Review by Ahmed Mahfoudh TSE

### Great Progress @webmarkyn  :clap: . However, some changes needs to be made in order for us to approve your project. check below :arrow_down: 

* [x] enumerables my_each returns an Enumerator if no block is given
* [x] enumerables my_each_with_index returns an enumerator if no block is given
* [x] enumerables my_select returns an enumerator if no block is given
- `my_each, my_each_with_index, my_select` Should return an enumerator if no block is giving.
  - Self is not an Enumerator, check this [guide](https://blog.arkency.com/2014/01/ruby-to-enum-for-enumerator/) for mor info.

* [x] enumerables my_all? returns true if the block never returns false or nil
* [x] enumerables my_all? when no block or argument is given returns true when none of the collection members are false or nil
  - my_all? is returning false always.
* [x] enumerables my_map returns a new array with the results of running block once for every element in enum.
* [x] enumerables my_map returns an Enumerator if no block is given
  - Same thing as my_each
* [x] enumerables my_inject combines all elements of enum by applying a binary operation, specified by a block
  - You have an error in block's arguments proc & word. 
```
     argumentsNoMethodError:
       undefined method `length' for 0:Integer

```
* [x] enumerables my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method
  - A problem in the expected result.

### That's it :relieved: . Apply the required changes to your methods. When finished, kindly resubmit another code review form :pray:

2019-10-16 22:43 UTC, stratospherique requested changes
### Great work implementing the suggested requirements :clap: . However, after thoroughly testing your methods, some of your methods have other requirements to fulfill. check the code comments below :arrow_down: 

- **[REQUIRED]** delete uncessary comments from `main.rb`

### When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**Ahmed Mahfoudh**

2019-10-16 22:43 UTC, stratospherique commented on main.rb
> +  end
* [ ] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-10-16 22:43 UTC, stratospherique commented on main.rb
> +  end
* [ ] my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-10-16 22:43 UTC, stratospherique commented on main.rb
> +  end
* [ ] my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-10-16 22:43 UTC, stratospherique commented on main.rb
> +  end
* [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
* [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-10-16 22:43 UTC, stratospherique commented on main.rb
> +  end
* [ ] my_map returns a new array with the results of running block once for every element in enum.

2019-10-16 22:43 UTC, stratospherique commented on main.rb
> +  end
- Wrong method output

2019-10-16 22:43 UTC, stratospherique commented on main.rb
> +  end
- Take into consideration an array of strings
- Check method output in comparison to original method
an example ``Range.new(5,50).inject(2, :*)``

2019-10-17 01:11 UTC, Ispirett requested changes
Hey @webmarkyn  great work :+1:  :100:  with changes and work done with this project.
There is just one bug  :bug:  see below.

Please use the correct git-flow  when submitting projects this project should use gitflow  

`feature-branch -> development `
**status: changes required
Isaac Browne**

2019-10-17 01:11 UTC, Ispirett commented on main.rb
> +  end
When running this  ` array.my_inject { |sum, n| sum + n } == array.inject { |sum, n| sum + n }`
i get the following messages please address this issue.

```
  TypeError:
       no implicit conversion of Integer into String

```

2019-10-17 13:33 UTC, maelfosso approved these changes
# Congratulations :clap: You've done :smile: 

**The project is approved** :+1: You can go ahead and merge this branch.
Good luck with the next project.
The next time, Kindly implement the **Git flow** process.

Thanks
**Mael FOSSO**
[Github](https://github.com/maelfosso) | [Twitter](https://twitter.com/maelfosso)

2019-10-22 15:37 UTC, merged