Rspec
webmarkyn/ruby-solo-1 pull request #2
Opened 2019-10-22 16:44 UTC by geraldgsh

- Created Rspec test cases for 6 methods as specified in the Odin project

2019-10-22 17:44 UTC, maelfosso requested changes
# Not approved : Only one bug to fix :disappointed: 

Hello @geraldgsh @webmarkyn 

Nice work :clap: You really master **RSpec**
There is only one bug to fix. Please, check it.

Kindly make the changes and submit a new code review request.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com)

2019-10-22 17:44 UTC, maelfosso commented on spec/main_spec.rb
> +        expect(array2.my_each_with_index { |item, i| "#{item}: #{i}" }).to eql(0..1)
Do not match

```ruby
irb(main):008:0> array2.each_with_index { |item, i| "#{item} : #{i}" }
=> ["star", "wars"]
irb(main):009:0> array2.my_each_with_index { |item, i| "#{item} : #{i}" }
=> 0..1
irb(main):010:0> 
irb(main):025:0> array2.each_with_index { |item, i| "#{item} : #{i}" } == array2.my_each_with_index { |item, i| "#{item} : #{i}" } 
=> false

```

2019-10-22 19:50 UTC, geraldgsh commented
@maelfosso Noted with thanks. We'll make the amendments according and submit another request for code review.

2019-10-22 21:40 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: . However, you still have one issue to fix in order to get approval. check :arrow_down: 

- I cannot see any **linter checks**, follow this [guide](https://github.com/microverseinc/linters-config/tree/master/ruby)

That's it :relaxed: . When finished, kindly resubmit another code review request :pray: 

**Ahmed Mahfoudh**

2019-10-22 22:26 UTC, geraldgsh commented
![image](https://user-images.githubusercontent.com/29500109/67339488-e7b9fc00-f55d-11e9-9035-1faa78b058d8.png)

2019-10-22 22:28 UTC, geraldgsh commented
@stratospherique Unfortunately stickler for this Repo isn't working despite many attempts to troubleshoot it.

However, Rubocop lint test passed as illustrated in the screenshot above.

2019-10-23 07:12 UTC, wathigo approved these changes
## Hi Devs  :wave:  

**This is approved. You can move on :next_track_button:**  

_Good luck!
Reviewed by: **Simon Wathigo**_

2019-10-23 13:36 UTC, geraldgsh commented
Thanks, @wathigo. We'll proceed with the merge.

2019-10-23 13:36 UTC, merged